[project]
name = "Objektorientierung"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Luggi003",email = "al3320@mci4me.at"},
    {name = "Christoph Gleinser", email = "gc0453@mci4me.at"},
]
dependencies = [
    "Objektorientierung @ file:///${PROJECT_ROOT}/",
    "pandas>=3.0.3",
    "plotly>=6.8.0",
    "matplotlib>=3.11.0",
    "streamlit>=1.58.0",
]
requires-python = "==3.14.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
